"use client";

import { FormEvent, useState } from "react";
import { Copy, MailPlus, Pencil, RefreshCw, Search, ShieldCheck, UserCog, X } from "lucide-react";
import type { StaffRole } from "./lib/ironcore-api";

export type StaffRow = { id: string; name: string; email: string; role: StaffRole; branchId: string | null; employeeNumber: string; jobTitle: string | null; status: "active" | "suspended" | "inactive"; hiredAt: string | null };
export type InvitationRow = { id: string; email: string; role: StaffRole; branchId: string | null; employeeNumber: string; jobTitle: string | null; status: string; expiresAt: string };
export type NewStaffInvite = { email: string; role: StaffRole; employee_number: string; job_title?: string; home_branch_id?: string; expires_in_days: number };
export type StaffUpdate = { role: StaffRole; employee_number: string; job_title?: string | null; home_branch_id?: string | null; status: StaffRow["status"]; reason: string };
export type StaffData = { rows: StaffRow[]; invitations: InvitationRow[]; branches: Array<{ id: string; name: string }>; loading: boolean; error: string | null; actorRole: string; readOnly?: boolean; onReload: () => void; onInvite: (input: NewStaffInvite) => Promise<string>; onUpdate: (id: string, input: StaffUpdate) => Promise<void> };

const roleLabel = (role: string) => role.split("_").map((word) => word[0].toUpperCase() + word.slice(1)).join(" ");
const displayDate = (value: string | null) => value ? new Intl.DateTimeFormat("en-GB", { day: "2-digit", month: "short", year: "numeric" }).format(new Date(value)) : "Not set";
const operationalRoles: StaffRole[] = ["receptionist", "trainer"];
const allRoles: StaffRole[] = ["gym_owner", "gym_manager", ...operationalRoles];

export function StaffManagement({ data, query }: { data: StaffData; query: string }) {
  const [inviteOpen, setInviteOpen] = useState(false);
  const [editing, setEditing] = useState<StaffRow | null>(null);
  const search = query.toLowerCase();
  const rows = data.rows.filter((row) => `${row.name} ${row.email} ${row.employeeNumber} ${row.jobTitle ?? ""}`.toLowerCase().includes(search));
  const invitations = data.invitations.filter((row) => `${row.email} ${row.employeeNumber}`.toLowerCase().includes(search));
  const manager = data.actorRole === "gym_manager";
  const canEdit = (row: StaffRow) => !data.readOnly && (!manager || operationalRoles.includes(row.role));

  return <>
    <section className="module-heading"><div><p className="eyebrow">Access control</p><h2>Team & access</h2><p>{data.readOnly ? "Representative team records for product review." : "Manage tenant staff, branch placement and time-limited invitations."}</p></div>{!data.readOnly && <button className="primary-button" onClick={() => setInviteOpen(true)}><MailPlus size={18} /> Invite staff</button>}</section>
    <div className="live-scope-banner"><ShieldCheck size={17} /><span><strong>Tenant role boundary active</strong><small>Managers can administer operational staff only; all sensitive updates require an audit reason.</small></span></div>
    {data.loading && <div className="table-state"><RefreshCw className="spin" size={20} /> Loading tenant team…</div>}
    {data.error && <div className="table-state error" role="alert"><strong>Team data could not be loaded</strong><span>{data.error}</span><button className="secondary-button" onClick={data.onReload}>Try again</button></div>}
    {!data.loading && !data.error && <>
      <section className="mini-metrics"><article><span>Staff profiles</span><strong>{data.rows.length}</strong><small>Tenant-scoped users</small></article><article><span>Active</span><strong>{data.rows.filter((r) => r.status === "active").length}</strong><small>Current team access</small></article><article><span>Pending invites</span><strong>{data.invitations.length}</strong><small>Hashed, time-limited tokens</small></article></section>
      <section className="panel table-scroll"><div className="panel-heading compact"><div><p className="eyebrow">Authorised users</p><h2>Staff directory</h2></div></div>{rows.length ? <table className="data-table"><thead><tr><th>Staff member</th><th>Employee no.</th><th>Role</th><th>Branch</th><th>Status</th><th /></tr></thead><tbody>{rows.map((row) => <tr key={row.id}><td><div className="person-cell"><span>{row.name.split(" ").map((p) => p[0]).join("").slice(0, 2)}</span><strong>{row.name}</strong></div><small className="table-sub">{row.email} · {row.jobTitle ?? "No job title"}</small></td><td>{row.employeeNumber}</td><td><span className="plan-pill">{roleLabel(row.role)}</span></td><td>{data.branches.find((b) => b.id === row.branchId)?.name ?? "All branches"}</td><td><span className={`status ${row.status}`}><i />{row.status}</span></td><td><button className="icon-button" disabled={!canEdit(row)} onClick={() => setEditing(row)} aria-label={`Edit ${row.name}`} title={!canEdit(row) ? "Managers cannot modify owners or other managers" : "Edit staff"}><Pencil size={17} /></button></td></tr>)}</tbody></table> : <Empty text="No staff found" />}</section>
      <section className="panel table-scroll"><div className="panel-heading compact"><div><p className="eyebrow">Secure onboarding</p><h2>Pending invitations</h2></div></div>{invitations.length ? <table className="data-table"><thead><tr><th>Email</th><th>Employee no.</th><th>Role</th><th>Branch</th><th>Expires</th></tr></thead><tbody>{invitations.map((row) => <tr key={row.id}><td><strong>{row.email}</strong><small className="table-sub">{row.jobTitle ?? "No job title"}</small></td><td>{row.employeeNumber}</td><td>{roleLabel(row.role)}</td><td>{data.branches.find((b) => b.id === row.branchId)?.name ?? "All branches"}</td><td>{displayDate(row.expiresAt)}</td></tr>)}</tbody></table> : <Empty text="No pending invitations" />}</section>
    </>}
    {inviteOpen && <InviteModal data={data} close={() => setInviteOpen(false)} />}
    {editing && <EditModal data={data} row={editing} close={() => setEditing(null)} />}
  </>;
}

function Empty({ text }: { text: string }) { return <div className="empty-state"><Search size={24} /><strong>{text}</strong><span>Records for this gym will appear here.</span></div>; }
function Shell({ title, close, children }: { title: string; close: () => void; children: React.ReactNode }) { return <div className="modal-layer" role="dialog" aria-modal="true"><button className="modal-scrim" onClick={close} aria-label="Close dialog" /><div className="modal-card"><div className="modal-heading"><span><UserCog size={21} /></span><div><p className="eyebrow">Tenant access</p><h2>{title}</h2></div><button className="icon-button" onClick={close} aria-label="Close"><X size={19} /></button></div>{children}</div></div>; }

function InviteModal({ data, close }: { data: StaffData; close: () => void }) {
  const [busy, setBusy] = useState(false); const [error, setError] = useState<string | null>(null); const [link, setLink] = useState<string | null>(null); const roles = data.actorRole === "gym_manager" ? operationalRoles : allRoles;
  async function submit(event: FormEvent<HTMLFormElement>) { event.preventDefault(); const form = new FormData(event.currentTarget); setBusy(true); setError(null); try { setLink(await data.onInvite({ email: String(form.get("email")), role: String(form.get("role")) as StaffRole, employee_number: String(form.get("employee_number")), job_title: String(form.get("job_title")) || undefined, home_branch_id: String(form.get("branch")) || undefined, expires_in_days: Number(form.get("expires")) })); } catch (reason) { setError(reason instanceof Error ? reason.message : "Invitation could not be created."); } finally { setBusy(false); } }
  return <Shell title={link ? "Invitation created" : "Invite staff member"} close={close}>{link ? <><div className="modal-note"><ShieldCheck size={17} />This one-time acceptance link is shown only now. Send it securely to the invited email address.</div><label>Acceptance link<textarea readOnly rows={4} value={link} /></label><div className="modal-actions"><button className="secondary-button" onClick={() => void navigator.clipboard.writeText(link)}><Copy size={16} /> Copy link</button><button className="primary-button" onClick={close}>Done</button></div></> : <form onSubmit={submit}>{error && <div className="form-error" role="alert">{error}</div>}<label>Email<input name="email" type="email" required autoFocus /></label><div className="field-pair"><label>Role<select name="role">{roles.map((role) => <option value={role} key={role}>{roleLabel(role)}</option>)}</select></label><label>Employee no.<input name="employee_number" required pattern="[A-Za-z0-9_-]+" /></label></div><label>Job title<input name="job_title" maxLength={120} /></label><div className="field-pair"><label>Home branch<select name="branch"><option value="">All branches</option>{data.branches.map((b) => <option value={b.id} key={b.id}>{b.name}</option>)}</select></label><label>Expires in<select name="expires" defaultValue="7"><option value="1">1 day</option><option value="3">3 days</option><option value="7">7 days</option><option value="14">14 days</option><option value="30">30 days</option></select></label></div><div className="modal-note"><ShieldCheck size={17} />The server stores only a SHA-256 token hash and never stores the acceptance secret.</div><div className="modal-actions"><button type="button" className="secondary-button" onClick={close}>Cancel</button><button disabled={busy} className="primary-button">{busy ? "Creating…" : "Create invitation"}</button></div></form>}</Shell>;
}

function EditModal({ data, row, close }: { data: StaffData; row: StaffRow; close: () => void }) {
  const [busy, setBusy] = useState(false); const [error, setError] = useState<string | null>(null); const roles = data.actorRole === "gym_manager" ? operationalRoles : allRoles;
  async function submit(event: FormEvent<HTMLFormElement>) { event.preventDefault(); const form = new FormData(event.currentTarget); setBusy(true); setError(null); try { await data.onUpdate(row.id, { role: String(form.get("role")) as StaffRole, employee_number: String(form.get("employee_number")), job_title: String(form.get("job_title")) || null, home_branch_id: String(form.get("branch")) || null, status: String(form.get("status")) as StaffRow["status"], reason: String(form.get("reason")) }); close(); } catch (reason) { setError(reason instanceof Error ? reason.message : "Staff could not be updated."); } finally { setBusy(false); } }
  return <Shell title={`Edit ${row.name}`} close={close}><form onSubmit={submit}>{error && <div className="form-error" role="alert">{error}</div>}<div className="field-pair"><label>Role<select name="role" defaultValue={row.role}>{roles.map((role) => <option value={role} key={role}>{roleLabel(role)}</option>)}</select></label><label>Status<select name="status" defaultValue={row.status}><option value="active">Active</option><option value="suspended">Suspended</option><option value="inactive">Inactive</option></select></label></div><div className="field-pair"><label>Employee no.<input name="employee_number" defaultValue={row.employeeNumber} required /></label><label>Job title<input name="job_title" defaultValue={row.jobTitle ?? ""} /></label></div><label>Home branch<select name="branch" defaultValue={row.branchId ?? ""}><option value="">All branches</option>{data.branches.map((b) => <option value={b.id} key={b.id}>{b.name}</option>)}</select></label><label>Audit reason<textarea name="reason" required maxLength={500} placeholder="Explain why this access change is required" /></label><div className="modal-note"><ShieldCheck size={17} />Role and status changes are tenant-bound and written to the immutable audit trail.</div><div className="modal-actions"><button type="button" className="secondary-button" onClick={close}>Cancel</button><button disabled={busy} className="primary-button">{busy ? "Saving…" : "Save changes"}</button></div></form></Shell>;
}
