"use client";

import { FormEvent, useState } from "react";
import { Building2, CircleDollarSign, Dumbbell, Plus, RefreshCw, Search, ShieldCheck, X } from "lucide-react";

export type OperationBranch = { id: string; name: string; code: string; email: string | null; phone: string | null; status: string; isPrimary: boolean };
export type OperationPlan = { id: string; branchId: string | null; name: string; code: string; interval: string; intervalCount: number; priceMinor: number; currency: string; status: string };
export type OperationMembership = { id: string; memberId: string; planId: string; status: string; startsAt: string; nextBillingAt: string | null; priceMinor: number; currency: string };
export type NewOperationBranch = { name: string; code: string; email?: string; phone?: string; is_primary?: boolean };
export type NewOperationPlan = { name: string; code: string; branch_id?: string; billing_interval: "one_time" | "weekly" | "monthly" | "quarterly" | "yearly"; interval_count: number; price_amount_minor: number; currency: "GBP" | "USD" | "PKR" | "AED" | "SAR"; joining_fee_minor: number; status: "active" };
export type NewOperationMembership = { member_id: string; plan_id: string; branch_id?: string; starts_at: string; status: "pending" | "active"; auto_renew: boolean };
export type OperationData = { branches: OperationBranch[]; plans: OperationPlan[]; memberships: OperationMembership[]; members: Array<{ id: string; name: string }>; loading: boolean; error: string | null; baseCurrency: NewOperationPlan["currency"]; canManageSetup: boolean; canManageMemberships: boolean; preview?: boolean; onReload: () => void; onCreateBranch: (v: NewOperationBranch) => Promise<void>; onCreatePlan: (v: NewOperationPlan) => Promise<void>; onCreateMembership: (v: NewOperationMembership) => Promise<void> };

export function decimalToMinor(value: string): number {
  // All supported currencies currently use two minor digits. String parsing
  // prevents binary floating-point drift before integer storage in PostgreSQL.
  const match = value.trim().match(/^(\d+)(?:\.(\d{0,2}))?$/);
  if (!match) throw new Error("Enter a valid amount with up to two decimals.");
  return Number(match[1]) * 100 + Number((match[2] ?? "").padEnd(2, "0"));
}
const cash = (minor: number, currency: string) => new Intl.NumberFormat("en", { style: "currency", currency }).format(minor / 100);
const date = (value: string | null) => value ? new Intl.DateTimeFormat("en-GB", { day: "2-digit", month: "short", year: "numeric" }).format(new Date(value)) : "Not scheduled";
function billingLabel(interval: string, count: number): string {
  const single: Record<string, string> = { one_time: "One time", weekly: "Weekly", monthly: "Monthly", quarterly: "Quarterly", yearly: "Yearly" };
  if (count === 1) return single[interval] ?? interval.replaceAll("_", " ");
  const units: Record<string, string> = { weekly: "weeks", monthly: "months", quarterly: "quarters", yearly: "years" };
  return `Every ${count} ${units[interval] ?? interval.replaceAll("_", " ")}`;
}

function Heading({ title, text, add }: { title: string; text: string; add?: () => void }) { const noun = title === "Membership plans" ? "plan" : title === "Branches" ? "branch" : "membership"; return <section className="module-heading"><div><p className="eyebrow">Tenant operations</p><h2>{title}</h2><p>{text}</p></div>{add && <button className="primary-button" onClick={add}><Plus size={18} /> Add {noun}</button>}</section>; }
function Scope({ preview = false }: { preview?: boolean }) { return <div className="live-scope-banner"><ShieldCheck size={17} /><span><strong>{preview ? "Representative preview" : "Live tenant data"}</strong><small>{preview ? "Sample records stay isolated from authenticated gym data." : "Route, header, policy and PostgreSQL RLS checks protect every request."}</small></span></div>; }
function Body({ data, children }: { data: OperationData; children: React.ReactNode }) { if (data.loading) return <div className="table-state"><RefreshCw className="spin" size={20} /> Loading tenant operations…</div>; if (data.error) return <div className="table-state error" role="alert"><strong>Data could not be loaded</strong><span>{data.error}</span><button className="secondary-button" onClick={data.onReload}>Try again</button></div>; return <section className="panel table-scroll">{children}</section>; }
function Empty({ name }: { name: string }) { return <div className="empty-state"><Search size={24} /><strong>No {name} yet</strong><span>Create the first record for this gym.</span></div>; }

export function BranchesView({ data, query }: { data: OperationData; query: string }) { const [open, setOpen] = useState(false); const rows = data.branches.filter((v) => `${v.name} ${v.code}`.toLowerCase().includes(query.toLowerCase())); return <><Heading title="Branches" text="Manage tenant-owned locations and operational status." add={data.canManageSetup ? () => setOpen(true) : undefined} /><Scope preview={data.preview} /><Body data={data}>{rows.length ? <table className="data-table"><thead><tr><th>Branch</th><th>Code</th><th>Contact</th><th>Type</th><th>Status</th></tr></thead><tbody>{rows.map((v) => <tr key={v.id}><td><strong>{v.name}</strong></td><td><span className="plan-pill">{v.code}</span></td><td>{v.email ?? v.phone ?? "Not set"}</td><td>{v.isPrimary ? "Primary" : "Location"}</td><td><span className={`status ${v.status}`}><i />{v.status}</span></td></tr>)}</tbody></table> : <Empty name="branches" />}</Body>{open && <BranchModal data={data} close={() => setOpen(false)} />}</>; }
export function PlansView({ data, query }: { data: OperationData; query: string }) { const [open, setOpen] = useState(false); const rows = data.plans.filter((v) => `${v.name} ${v.code}`.toLowerCase().includes(query.toLowerCase())); return <><Heading title="Membership plans" text="Configure branch-aware recurring prices in exact minor units." add={data.canManageSetup ? () => setOpen(true) : undefined} /><Scope preview={data.preview} /><Body data={data}>{rows.length ? <table className="data-table"><thead><tr><th>Plan</th><th>Scope</th><th>Billing</th><th>Price</th><th>Status</th></tr></thead><tbody>{rows.map((v) => <tr key={v.id}><td><strong>{v.name}</strong><small className="table-sub">{v.code}</small></td><td>{data.branches.find((b) => b.id === v.branchId)?.name ?? "All branches"}</td><td>{billingLabel(v.interval, v.intervalCount)}</td><td><strong>{cash(v.priceMinor, v.currency)}</strong></td><td><span className={`status ${v.status}`}><i />{v.status}</span></td></tr>)}</tbody></table> : <Empty name="plans" />}</Body>{open && <PlanModal data={data} close={() => setOpen(false)} />}</>; }
export function MembershipsView({ data, query }: { data: OperationData; query: string }) { const [open, setOpen] = useState(false); const member = (id: string) => data.members.find((v) => v.id === id)?.name ?? "Unknown member"; const rows = data.memberships.filter((v) => `${member(v.memberId)} ${v.status}`.toLowerCase().includes(query.toLowerCase())); return <><Heading title="Memberships" text="Activate members from immutable plan and price snapshots." add={data.canManageMemberships && data.members.length > 0 && data.plans.length > 0 ? () => setOpen(true) : undefined} /><Scope preview={data.preview} /><Body data={data}>{rows.length ? <table className="data-table"><thead><tr><th>Member</th><th>Plan</th><th>Accepted price</th><th>Started</th><th>Next billing</th><th>Status</th></tr></thead><tbody>{rows.map((v) => <tr key={v.id}><td><strong>{member(v.memberId)}</strong></td><td>{data.plans.find((p) => p.id === v.planId)?.name ?? "Archived plan"}</td><td>{cash(v.priceMinor, v.currency)}</td><td>{date(v.startsAt)}</td><td>{date(v.nextBillingAt)}</td><td><span className={`status ${v.status}`}><i />{v.status}</span></td></tr>)}</tbody></table> : <Empty name="memberships" />}</Body>{open && <MembershipModal data={data} close={() => setOpen(false)} />}</>; }

function Modal({ title, icon: Icon, close, save, children }: { title: string; icon: typeof Building2; close: () => void; save: (d: FormData) => Promise<void>; children: React.ReactNode }) { const [busy, setBusy] = useState(false); const [error, setError] = useState<string | null>(null); async function submit(e: FormEvent<HTMLFormElement>) { e.preventDefault(); setBusy(true); setError(null); try { await save(new FormData(e.currentTarget)); close(); } catch (reason) { setError(reason instanceof Error ? reason.message : "Creation failed."); } finally { setBusy(false); } } return <div className="modal-layer" role="dialog" aria-modal="true"><button className="modal-scrim" onClick={close} aria-label="Close dialog" /><form className="modal-card" onSubmit={submit}><div className="modal-heading"><span><Icon size={21} /></span><div><p className="eyebrow">Tenant record</p><h2>{title}</h2></div><button type="button" className="icon-button" onClick={close}><X size={19} /></button></div>{error && <div className="form-error">{error}</div>}{children}<div className="modal-note"><ShieldCheck size={17} />Gym ownership is assigned from the verified server tenant context.</div><div className="modal-actions"><button type="button" className="secondary-button" onClick={close}>Cancel</button><button disabled={busy} className="primary-button">{busy ? "Creating…" : "Create"}</button></div></form></div>; }
function BranchModal({ data, close }: { data: OperationData; close: () => void }) { return <Modal title="Add branch" icon={Building2} close={close} save={(d) => data.onCreateBranch({ name: String(d.get("name")), code: String(d.get("code")), email: String(d.get("email")) || undefined, phone: String(d.get("phone")) || undefined, is_primary: d.get("primary") === "on" })}><label>Name<input name="name" required autoFocus /></label><label>Code<input name="code" required pattern="[A-Za-z0-9_-]+" /></label><div className="field-pair"><label>Email<input name="email" type="email" /></label><label>Phone<input name="phone" /></label></div><label><input name="primary" type="checkbox" /> Primary branch</label></Modal>; }
function PlanModal({ data, close }: { data: OperationData; close: () => void }) { return <Modal title="Add membership plan" icon={CircleDollarSign} close={close} save={(d) => data.onCreatePlan({ name: String(d.get("name")), code: String(d.get("code")), branch_id: String(d.get("branch")) || undefined, billing_interval: String(d.get("interval")) as NewOperationPlan["billing_interval"], interval_count: Number(d.get("count")), price_amount_minor: decimalToMinor(String(d.get("price"))), joining_fee_minor: decimalToMinor(String(d.get("fee") || "0")), currency: data.baseCurrency, status: "active" })}><div className="field-pair"><label>Name<input name="name" required autoFocus /></label><label>Code<input name="code" required /></label></div><label>Branch<select name="branch"><option value="">All branches</option>{data.branches.map((v) => <option key={v.id} value={v.id}>{v.name}</option>)}</select></label><div className="field-pair"><label>Interval<select name="interval"><option value="one_time">One time</option><option value="weekly">Weekly</option><option value="monthly">Monthly</option><option value="quarterly">Quarterly</option><option value="yearly">Yearly</option></select></label><label>Every<input name="count" type="number" min="1" max="52" defaultValue="1" required /></label></div><div className="field-pair"><label>Price ({data.baseCurrency})<input name="price" inputMode="decimal" required /></label><label>Joining fee<input name="fee" inputMode="decimal" defaultValue="0" /></label></div></Modal>; }
function MembershipModal({ data, close }: { data: OperationData; close: () => void }) { return <Modal title="Create membership" icon={Dumbbell} close={close} save={(d) => data.onCreateMembership({ member_id: String(d.get("member")), plan_id: String(d.get("plan")), branch_id: String(d.get("branch")) || undefined, starts_at: String(d.get("starts")), status: String(d.get("status")) as "active" | "pending", auto_renew: d.get("renew") === "on" })}><label>Member<select name="member">{data.members.map((v) => <option key={v.id} value={v.id}>{v.name}</option>)}</select></label><label>Plan<select name="plan">{data.plans.filter((v) => v.status === "active").map((v) => <option key={v.id} value={v.id}>{v.name} · {cash(v.priceMinor, v.currency)}</option>)}</select></label><label>Branch<select name="branch"><option value="">Plan/default branch</option>{data.branches.map((v) => <option key={v.id} value={v.id}>{v.name}</option>)}</select></label><div className="field-pair"><label>Starts<input name="starts" type="date" defaultValue={new Date().toISOString().slice(0, 10)} required /></label><label>Status<select name="status"><option value="active">Active</option><option value="pending">Pending</option></select></label></div><label><input name="renew" type="checkbox" defaultChecked /> Auto renew</label></Modal>; }
