"use client";

import { FormEvent, useState } from "react";
import { ArrowLeft, Building2, CalendarPlus, CircleDollarSign, Dumbbell, Eye, MoreHorizontal, Pencil, Plus, RefreshCw, Search, ShieldCheck, Trash2, UserCog, UsersRound, X } from "lucide-react";
import type { AttendanceRecord, ClassSessionRecord, NewClassSession } from "./lib/ironcore-api";
import { zonedLocalDateTimeToIso } from "./lib/gym-time";
import { timezoneOptions } from "./gym-location-options";
import { SearchableSelect } from "./searchable-select";

export type OperationBranch = { id: string; name: string; code: string; email: string | null; phone: string | null; timezone: string | null; status: string; isPrimary: boolean };
export type OperationPlan = { id: string; branchId: string | null; name: string; code: string; description: string | null; interval: string; intervalCount: number; priceMinor: number; currency: string; durationDays: number | null; trialDays: number; status: string };
export type OperationMembership = { id: string; memberId: string; planId: string; status: "pending" | "active" | "paused" | "cancelled" | "expired"; startsAt: string; endsAt: string | null; nextBillingAt: string | null; priceMinor: number; currency: string; autoRenew: boolean };
export type NewOperationBranch = { name: string; code: string; email?: string; phone?: string; timezone?: string; is_primary?: boolean };
export type NewOperationPlan = { name: string; code: string; branch_id?: string; description?: string; billing_interval: "one_time" | "weekly" | "monthly" | "quarterly" | "yearly"; interval_count: number; price_amount_minor: number; currency: "GBP" | "USD" | "PKR" | "AED" | "SAR"; joining_fee_minor: number; duration_days?: number; trial_days?: number; status: "active" };
export type NewOperationMembership = { member_id: string; plan_id: string; branch_id?: string; starts_at: string; ends_at?: string; status: "pending" | "active"; auto_renew: boolean };
export type UpdateOperationBranch = { name: string; code: string; email?: string | null; phone?: string | null; timezone?: string | null; status: "active" | "inactive"; is_primary: boolean; reason: string };
export type UpdateOperationPlan = { name: string; code: string; branch_id?: string | null; description?: string | null; price_amount_minor: number; currency: NewOperationPlan["currency"]; duration_days?: number | null; trial_days?: number; status: "active" | "inactive"; reason: string };
export type UpdateOperationMembership = { status: OperationMembership["status"]; ends_at?: string | null; next_billing_at?: string | null; auto_renew: boolean; cancellation_reason?: string | null; reason: string };
export type OperationMember = { id: string; name: string; memberCode: string; branchId?: string | null; status?: string };
export type OperationStaff = { id: string; name: string; role: string; branchId: string | null; status: string };
export type OperationData = { branches: OperationBranch[]; plans: OperationPlan[]; memberships: OperationMembership[]; members: OperationMember[]; staff?: OperationStaff[]; sessions?: ClassSessionRecord[]; attendance?: AttendanceRecord[]; loading: boolean; error: string | null; baseCurrency: NewOperationPlan["currency"]; gymTimezone: string; canManageSetup: boolean; canManageMemberships: boolean; preview?: boolean; onReload: () => void; onCreateBranch: (v: NewOperationBranch) => Promise<void>; onUpdateBranch: (id: string, v: UpdateOperationBranch) => Promise<void>; onDeleteBranch?: (id: string, reason: string) => Promise<void>; onAssignBranchMember?: (memberId: string, branchId: string | null, reason: string) => Promise<void>; onAssignBranchStaff?: (staffId: string, branchId: string | null, reason: string) => Promise<void>; onCreateClassSession?: (input: NewClassSession) => Promise<void>; onCreatePlan: (v: NewOperationPlan) => Promise<void>; onUpdatePlan: (id: string, v: UpdateOperationPlan) => Promise<void>; onCreateMembership: (v: NewOperationMembership) => Promise<void>; onUpdateMembership: (id: string, v: UpdateOperationMembership) => Promise<void> };

export function decimalToMinor(value: string): number {
  // All supported currencies currently use two minor digits. String parsing
  // prevents binary floating-point drift before integer storage in PostgreSQL.
  const match = value.trim().match(/^(\d+)(?:\.(\d{0,2}))?$/);
  if (!match) throw new Error("Enter a valid amount with up to two decimals.");
  return Number(match[1]) * 100 + Number((match[2] ?? "").padEnd(2, "0"));
}
const cash = (minor: number, currency: string) => new Intl.NumberFormat("en", { style: "currency", currency }).format(minor / 100);
const date = (value: string | null) => value ? new Intl.DateTimeFormat("en-GB", { day: "2-digit", month: "short", year: "numeric" }).format(new Date(value)) : "Not scheduled";
function billingLabel(interval: string, count: number): string {
  const single: Record<string, string> = { one_time: "One time", weekly: "Weekly", monthly: "Monthly", quarterly: "Quarterly", yearly: "Yearly" };
  if (count === 1) return single[interval] ?? interval.replaceAll("_", " ");
  const units: Record<string, string> = { weekly: "weeks", monthly: "months", quarterly: "quarters", yearly: "years" };
  return `Every ${count} ${units[interval] ?? interval.replaceAll("_", " ")}`;
}

function Heading({ title, text, add }: { title: string; text: string; add?: () => void }) { const noun = title === "Membership plans" ? "plan" : title === "Branches" ? "branch" : "membership"; return <section className="module-heading"><div><p className="eyebrow">Tenant operations</p><h2>{title}</h2><p>{text}</p></div>{add && <button className="primary-button" onClick={add}><Plus size={18} /> Add {noun}</button>}</section>; }
function Scope({ preview = false }: { preview?: boolean }) { return <div className="live-scope-banner"><ShieldCheck size={17} /><span><strong>{preview ? "Representative preview" : "Live tenant data"}</strong><small>{preview ? "Sample records stay isolated from authenticated gym data." : "Route, header, policy and PostgreSQL RLS checks protect every request."}</small></span></div>; }
function Body({ data, children }: { data: OperationData; children: React.ReactNode }) { if (data.loading) return <div className="table-state"><RefreshCw className="spin" size={20} /> Loading tenant operations…</div>; if (data.error) return <div className="table-state error" role="alert"><strong>Data could not be loaded</strong><span>{data.error}</span><button className="secondary-button" onClick={data.onReload}>Try again</button></div>; return <section className="panel table-scroll">{children}</section>; }
function Empty({ name }: { name: string }) { return <div className="empty-state"><Search size={24} /><strong>No {name} yet</strong><span>Create the first record for this gym.</span></div>; }

export function BranchesView({ data, query }: { data: OperationData; query: string }) {
  const [open, setOpen] = useState(false);
  const [editingId, setEditingId] = useState<string | null>(null);
  const [selectedId, setSelectedId] = useState<string | null>(null);
  const rows = data.branches.filter((v) => `${v.name} ${v.code}`.toLowerCase().includes(query.toLowerCase()));
  const editing = data.branches.find((branch) => branch.id === editingId) ?? null;
  const selected = data.branches.find((branch) => branch.id === selectedId) ?? null;

  if (selected) return <><BranchWorkspace data={data} branch={selected} back={() => setSelectedId(null)} edit={() => setEditingId(selected.id)} deleted={() => setSelectedId(null)} />{editing && <EditBranchModal data={data} branch={editing} close={() => setEditingId(null)} />}</>;

  return <><Heading title="Branches" text="Manage locations, teams, members, classes and attendance from one tenant-safe workspace." add={data.canManageSetup ? () => setOpen(true) : undefined} /><Scope preview={data.preview} /><Body data={data}>{rows.length ? <table className="data-table"><thead><tr><th>Branch</th><th>Code</th><th>Contact</th><th>Type</th><th>Status</th><th>Actions</th></tr></thead><tbody>{rows.map((v) => <tr key={v.id}><td><strong>{v.name}</strong></td><td><span className="plan-pill">{v.code}</span></td><td>{v.email ?? v.phone ?? "Not set"}</td><td>{v.isPrimary ? "Primary" : "Location"}</td><td><span className={`status ${v.status}`}><i />{v.status}</span></td><td><div className="branch-row-actions"><button className="table-action" onClick={() => setSelectedId(v.id)} aria-label={`View ${v.name}`}><Eye size={13} /> View</button>{data.canManageSetup && <button className="table-action" onClick={() => setEditingId(v.id)} aria-label={`Edit ${v.name}`}><Pencil size={13} /> Edit</button>}<button className="icon-button" onClick={() => setSelectedId(v.id)} aria-label={`Manage ${v.name}`} title="Open branch workspace"><MoreHorizontal size={17} /></button></div></td></tr>)}</tbody></table> : <Empty name="branches" />}</Body>{open && <BranchModal data={data} close={() => setOpen(false)} />}{editing && <EditBranchModal data={data} branch={editing} close={() => setEditingId(null)} />}</>;
}

function BranchWorkspace({ data, branch, back, edit, deleted }: { data: OperationData; branch: OperationBranch; back: () => void; edit: () => void; deleted: () => void }) {
  const [teamOpen, setTeamOpen] = useState(false);
  const [memberOpen, setMemberOpen] = useState(false);
  const [classOpen, setClassOpen] = useState(false);
  const [action, setAction] = useState<"status" | "delete" | null>(null);
  const [notice, setNotice] = useState<string | null>(null);
  const [error, setError] = useState<string | null>(null);
  const staff = (data.staff ?? []).filter((row) => row.branchId === branch.id);
  const trainers = staff.filter((row) => row.role === "trainer");
  const members = data.members.filter((row) => row.branchId === branch.id);
  const sessions = (data.sessions ?? []).filter((row) => row.branch_id === branch.id);
  const attendance = (data.attendance ?? []).filter((row) => row.branch_id === branch.id);
  const canManage = data.canManageSetup && !data.preview;

  async function changeStatus(reason: string) {
    setError(null);
    try {
      const next = branch.status === "active" ? "inactive" : "active";
      await data.onUpdateBranch(branch.id, { name: branch.name, code: branch.code, email: branch.email, phone: branch.phone, timezone: branch.timezone, status: next, is_primary: branch.isPrimary, reason });
      setNotice(`Branch ${next === "active" ? "activated" : "deactivated"}.`);
      setAction(null);
    } catch (reasonValue) { setError(reasonValue instanceof Error ? reasonValue.message : "Branch status could not be changed."); }
  }

  async function removeBranch(reason: string) {
    if (!data.onDeleteBranch) return;
    setError(null);
    try { await data.onDeleteBranch(branch.id, reason); setAction(null); deleted(); }
    catch (reasonValue) { setError(reasonValue instanceof Error ? reasonValue.message : "The branch could not be deleted."); }
  }

  return <section className="branch-workspace">
    <header className="panel branch-workspace-head">
      <div className="branch-workspace-toolbar">
        <button className="branch-back-button" onClick={back}><ArrowLeft size={16} /> Back to branches</button>
        <div className="branch-workspace-actions">{canManage && <><button className="secondary-button" onClick={edit}><Pencil size={15} /> Edit branch</button><button className="secondary-button" onClick={() => setAction("status")}>{branch.status === "active" ? "Deactivate" : "Activate"}</button>{data.onDeleteBranch && <button className="danger-button" disabled={branch.isPrimary} onClick={() => setAction("delete")} title={branch.isPrimary ? "Primary branches cannot be deleted" : "Delete only if no records are linked"}><Trash2 size={15} /> Delete unused</button>}</>}</div>
      </div>
      <div className="branch-workspace-identity">
        <span className="branch-workspace-mark"><Building2 size={23} /></span>
        <div><p className="branch-context-label">Branch workspace</p><h2>{branch.name}</h2><div className="branch-workspace-meta"><span>Code <strong>{branch.code}</strong></span><span>Timezone <strong>{branch.timezone ?? data.gymTimezone}</strong></span><span className={`status ${branch.status}`}><i />{branch.status}</span></div></div>
      </div>
    </header>
    <Scope preview={data.preview} />
    {notice && <div className="form-notice" role="status">{notice}</div>}{error && <div className="form-error" role="alert">{error}</div>}
    <div className="branch-metrics"><article className="panel"><span className="branch-metric-icon"><UsersRound size={19} /></span><span><small>Linked members</small><strong>{members.length}</strong><p>Using this home branch</p></span></article><article className="panel"><span className="branch-metric-icon"><UserCog size={19} /></span><span><small>Staff and trainers</small><strong>{staff.length}</strong><p>{trainers.length} {trainers.length === 1 ? "trainer" : "trainers"} assigned</p></span></article><article className="panel"><span className="branch-metric-icon"><CalendarPlus size={19} /></span><span><small>Classes</small><strong>{sessions.length}</strong><p>In the visible schedule</p></span></article><article className="panel"><span className="branch-metric-icon"><ShieldCheck size={19} /></span><span><small>Attendance</small><strong>{attendance.length}</strong><p>Recent branch visits</p></span></article></div>
    <div className="branch-workspace-grid">
      <article className="panel branch-overview-card"><div className="branch-section-heading"><div><h3>Branch details</h3><p>Contact and operating information for this location.</p></div><span className={`status ${branch.status}`}><i />{branch.status}</span></div><dl><div><dt>Branch code</dt><dd>{branch.code}</dd></div><div><dt>Type</dt><dd>{branch.isPrimary ? "Primary branch" : "Location"}</dd></div><div><dt>Email</dt><dd>{branch.email ?? "Not set"}</dd></div><div><dt>Phone</dt><dd>{branch.phone ?? "Not set"}</dd></div><div><dt>Timezone</dt><dd>{branch.timezone ?? data.gymTimezone}</dd></div></dl></article>
      <BranchCollection title="Staff and trainers" description="People assigned to work at this branch." action={canManage && data.onAssignBranchStaff ? <button className="secondary-button" onClick={() => setTeamOpen(true)}><UserCog size={15} /> Manage team</button> : null}>{staff.length ? <ul>{staff.map((row) => <li key={row.id}><span><strong>{row.name}</strong><small>{row.role.replaceAll("_", " ")}</small></span><span className={`status ${row.status}`}><i />{row.status}</span></li>)}</ul> : <BranchEmpty text="No staff assigned to this branch." action={canManage && data.onAssignBranchStaff ? <button className="table-action" onClick={() => setTeamOpen(true)}>Assign staff or trainer</button> : null} />}</BranchCollection>
      <BranchCollection title="Linked members" description="Members whose home location is this branch." action={canManage && data.onAssignBranchMember ? <button className="secondary-button" onClick={() => setMemberOpen(true)}><UsersRound size={15} /> Manage members</button> : null}>{members.length ? <ul>{members.map((row) => <li key={row.id}><span><strong>{row.name}</strong><small>Member Code {row.memberCode}</small></span><span className={`status ${row.status ?? "active"}`}><i />{row.status ?? "active"}</span></li>)}</ul> : <BranchEmpty text="No members use this as their home branch." action={canManage && data.onAssignBranchMember ? <button className="table-action" onClick={() => setMemberOpen(true)}>Link a member</button> : null} />}</BranchCollection>
      <BranchCollection title="Classes" description="Upcoming and recent sessions at this location." action={canManage && branch.status === "active" && data.onCreateClassSession ? <button className="primary-button" onClick={() => setClassOpen(true)}><Plus size={15} /> Schedule class</button> : null}>{sessions.length ? <ul>{sessions.slice(0, 8).map((row) => <li key={row.id}><span><strong>{row.title}</strong><small>{dateTime(row.starts_at)} · {row.booked_count}/{row.capacity} booked</small></span><span className={`status ${row.status}`}><i />{row.status}</span></li>)}</ul> : <BranchEmpty text="No classes are visible in the current schedule window." action={canManage && branch.status === "active" && data.onCreateClassSession ? <button className="table-action" onClick={() => setClassOpen(true)}>Schedule the first class</button> : null} />}</BranchCollection>
      <BranchCollection title="Attendance" description="Recent check-ins recorded at this branch.">{attendance.length ? <ul>{attendance.slice(0, 8).map((row) => <li key={row.id}><span><strong>{row.member?.name ?? "Member"}</strong><small>{dateTime(row.checked_in_at)} · {row.method.replaceAll("_", " ")}</small></span><span className={`status ${row.status}`}><i />{row.status.replaceAll("_", " ")}</span></li>)}</ul> : <BranchEmpty text="No attendance records are visible in the current date window." />}</BranchCollection>
    </div>
    {teamOpen && <BranchAssignmentModal kind="staff" branch={branch} rows={data.staff ?? []} close={() => setTeamOpen(false)} save={async (id, branchId, reason) => { await data.onAssignBranchStaff?.(id, branchId, reason); setTeamOpen(false); setNotice("Staff branch assignment saved."); }} />}
    {memberOpen && <BranchAssignmentModal kind="member" branch={branch} rows={data.members} close={() => setMemberOpen(false)} save={async (id, branchId, reason) => { await data.onAssignBranchMember?.(id, branchId, reason); setMemberOpen(false); setNotice("Member home branch saved."); }} />}
    {classOpen && <BranchClassModal data={data} branch={branch} trainers={(data.staff ?? []).filter((row) => row.role === "trainer" && row.status === "active" && row.branchId === branch.id)} close={() => setClassOpen(false)} />}
    {action === "status" && <BranchReasonModal title={`${branch.status === "active" ? "Deactivate" : "Activate"} ${branch.name}`} text={branch.status === "active" ? "New check-ins, bookings and classes will be blocked. Historical records remain available." : "This restores operational access for this branch."} confirm={branch.status === "active" ? "Deactivate branch" : "Activate branch"} close={() => setAction(null)} save={changeStatus} />}
    {action === "delete" && <BranchDeleteModal branch={branch} close={() => setAction(null)} save={removeBranch} />}
  </section>;
}

function BranchCollection({ title, description, action, children }: { title: string; description: string; action?: React.ReactNode; children: React.ReactNode }) { return <article className="panel branch-collection"><div className="branch-section-heading"><div><h3>{title}</h3><p>{description}</p></div>{action}</div>{children}</article>; }
function BranchEmpty({ text, action }: { text: string; action?: React.ReactNode }) { return <div className="branch-empty"><Search size={19} /><span>{text}</span>{action}</div>; }
function dateTime(value: string): string { return new Intl.DateTimeFormat("en-GB", { day: "2-digit", month: "short", hour: "2-digit", minute: "2-digit" }).format(new Date(value)); }
function nextDayClassDefaults(): { start: string; end: string } {
  const day = new Date(Date.now() + 86_400_000).toISOString().slice(0, 11);
  return { start: `${day}18:00`, end: `${day}19:00` };
}
export function PlansView({ data, query }: { data: OperationData; query: string }) { const [open, setOpen] = useState(false); const [editingId, setEditingId] = useState<string | null>(null); const rows = data.plans.filter((v) => `${v.name} ${v.code}`.toLowerCase().includes(query.toLowerCase())); const editing = data.plans.find((plan) => plan.id === editingId) ?? null; return <><Heading title="Membership plans" text="Configure branch-aware recurring prices in exact minor units." add={data.canManageSetup ? () => setOpen(true) : undefined} /><Scope preview={data.preview} /><Body data={data}>{rows.length ? <table className="data-table"><thead><tr><th>Plan</th><th>Scope</th><th>Billing</th><th>Price</th><th>Status</th>{data.canManageSetup && <th />}</tr></thead><tbody>{rows.map((v) => <tr key={v.id}><td><strong>{v.name}</strong><small className="table-sub">{v.code}</small></td><td>{data.branches.find((b) => b.id === v.branchId)?.name ?? "All branches"}</td><td>{billingLabel(v.interval, v.intervalCount)}<small className="table-sub">{v.durationDays ? `${v.durationDays} day access` : "No fixed expiry"}{v.trialDays ? ` · ${v.trialDays} day trial` : ""}</small></td><td><strong>{cash(v.priceMinor, v.currency)}</strong></td><td><span className={`status ${v.status}`}><i />{v.status}</span></td>{data.canManageSetup && <td><button className="table-action" onClick={() => setEditingId(v.id)} aria-label={`Edit ${v.name}`}><Pencil size={13} /> Edit</button></td>}</tr>)}</tbody></table> : <Empty name="plans" />}</Body>{open && <PlanModal data={data} close={() => setOpen(false)} />}{editing && <EditPlanModal data={data} plan={editing} close={() => setEditingId(null)} />}</>; }
export function MembershipsView({ data, query }: { data: OperationData; query: string }) { const [open, setOpen] = useState(false); const [editingId, setEditingId] = useState<string | null>(null); const member = (id: string) => data.members.find((v) => v.id === id)?.name ?? "Unknown member"; const rows = data.memberships.filter((v) => `${member(v.memberId)} ${v.status}`.toLowerCase().includes(query.toLowerCase())); const editing = data.memberships.find((membership) => membership.id === editingId) ?? null; return <><Heading title="Memberships" text="Activate members from immutable plan and price snapshots." add={data.canManageMemberships && data.members.length > 0 && data.plans.length > 0 ? () => setOpen(true) : undefined} /><Scope preview={data.preview} /><Body data={data}>{rows.length ? <table className="data-table"><thead><tr><th>Member</th><th>Plan</th><th>Accepted price</th><th>Started</th><th>Expires</th><th>Next billing</th><th>Status</th>{data.canManageMemberships && <th />}</tr></thead><tbody>{rows.map((v) => <tr key={v.id}><td><strong>{member(v.memberId)}</strong></td><td>{data.plans.find((p) => p.id === v.planId)?.name ?? "Archived plan"}</td><td>{cash(v.priceMinor, v.currency)}</td><td>{date(v.startsAt)}</td><td>{v.endsAt ? date(v.endsAt) : "No fixed expiry"}</td><td>{date(v.nextBillingAt)}</td><td><span className={`status ${v.status}`}><i />{v.status}</span></td>{data.canManageMemberships && <td><button className="table-action" onClick={() => setEditingId(v.id)} aria-label={`Edit ${member(v.memberId)} membership`}><Pencil size={13} /> Edit</button></td>}</tr>)}</tbody></table> : <Empty name="memberships" />}</Body>{open && <MembershipModal data={data} close={() => setOpen(false)} />}{editing && <EditMembershipModal data={data} membership={editing} memberName={member(editing.memberId)} close={() => setEditingId(null)} />}</>; }

function Modal({ title, icon: Icon, close, save, children }: { title: string; icon: typeof Building2; close: () => void; save: (d: FormData) => Promise<void>; children: React.ReactNode }) { const [busy, setBusy] = useState(false); const [error, setError] = useState<string | null>(null); async function submit(e: FormEvent<HTMLFormElement>) { e.preventDefault(); setBusy(true); setError(null); try { await save(new FormData(e.currentTarget)); close(); } catch (reason) { setError(reason instanceof Error ? reason.message : "Creation failed."); } finally { setBusy(false); } } return <div className="modal-layer" role="dialog" aria-modal="true"><button className="modal-scrim" onClick={close} aria-label="Close dialog" /><form className="modal-card" onSubmit={submit}><div className="modal-heading"><span><Icon size={21} /></span><div><p className="eyebrow">Tenant record</p><h2>{title}</h2></div><button type="button" className="icon-button" onClick={close}><X size={19} /></button></div>{error && <div className="form-error">{error}</div>}{children}<div className="modal-note"><ShieldCheck size={17} />Gym ownership is assigned from the verified server tenant context.</div><div className="modal-actions"><button type="button" className="secondary-button" onClick={close}>Cancel</button><button disabled={busy} className="primary-button">{busy ? "Creating…" : "Create"}</button></div></form></div>; }

function BranchAssignmentModal({ kind, branch, rows, close, save }: { kind: "staff" | "member"; branch: OperationBranch; rows: Array<{ id: string; name: string; branchId?: string | null }>; close: () => void; save: (id: string, branchId: string | null, reason: string) => Promise<void> }) {
  const [busy, setBusy] = useState(false); const [error, setError] = useState<string | null>(null);
  async function submit(event: FormEvent<HTMLFormElement>) { event.preventDefault(); const form = new FormData(event.currentTarget); setBusy(true); setError(null); try { await save(String(form.get("record")), form.get("assignment") === "assign" ? branch.id : null, String(form.get("reason"))); } catch (reason) { setError(reason instanceof Error ? reason.message : "The branch assignment could not be saved."); } finally { setBusy(false); } }
  return <div className="modal-layer" role="dialog" aria-modal="true" aria-label={`Manage branch ${kind}`}><button className="modal-scrim" onClick={close} aria-label="Close dialog" /><form className="modal-card branch-assignment-modal" onSubmit={submit}><div className="modal-heading"><span>{kind === "staff" ? <UserCog size={21} /> : <UsersRound size={21} />}</span><div><p className="eyebrow">Audited branch assignment</p><h2>Manage {kind} · {branch.name}</h2></div><button type="button" className="icon-button" onClick={close} aria-label="Close"><X size={19} /></button></div>{error && <div className="form-error" role="alert">{error}</div>}<label>{kind === "staff" ? "Staff member / trainer" : "Member"}<select name="record" required defaultValue=""><option value="" disabled>Select {kind}</option>{rows.map((row) => <option key={row.id} value={row.id}>{row.name}{row.branchId === branch.id ? " · currently assigned" : ""}</option>)}</select></label><label>Assignment<select name="assignment"><option value="assign">Assign to {branch.name}</option><option value="remove">Remove home branch assignment</option></select></label><label>Audit reason<textarea name="reason" required minLength={5} maxLength={500} placeholder={`Explain this ${kind} branch change`} /></label><div className="modal-note"><ShieldCheck size={17} />The backend verifies the selected record belongs to this gym before changing its branch.</div><div className="modal-actions"><button type="button" className="secondary-button" onClick={close}>Cancel</button><button disabled={busy || rows.length === 0} className="primary-button">{busy ? "Saving…" : "Save assignment"}</button></div></form></div>;
}

function BranchClassModal({ data, branch, trainers, close }: { data: OperationData; branch: OperationBranch; trainers: OperationStaff[]; close: () => void }) {
  const [busy, setBusy] = useState(false); const [error, setError] = useState<string | null>(null);
  const [defaults] = useState(nextDayClassDefaults);
  async function submit(event: FormEvent<HTMLFormElement>) { event.preventDefault(); if (!data.onCreateClassSession) return; const form = new FormData(event.currentTarget); setBusy(true); setError(null); try { await data.onCreateClassSession({ branch_id: branch.id, trainer_staff_profile_id: String(form.get("trainer")) || undefined, title: String(form.get("title")), description: String(form.get("description")) || undefined, starts_at: zonedLocalDateTimeToIso(String(form.get("starts")), branch.timezone ?? data.gymTimezone), ends_at: zonedLocalDateTimeToIso(String(form.get("ends")), branch.timezone ?? data.gymTimezone), capacity: Number(form.get("capacity")), waitlist_enabled: form.get("waitlist") === "on" }); close(); } catch (reason) { setError(reason instanceof Error ? reason.message : "The class could not be scheduled."); } finally { setBusy(false); } }
  return <div className="modal-layer" role="dialog" aria-modal="true" aria-label={`Schedule class at ${branch.name}`}><button className="modal-scrim" onClick={close} aria-label="Close dialog" /><form className="modal-card branch-class-modal" onSubmit={submit}><div className="modal-heading"><span><CalendarPlus size={21} /></span><div><p className="eyebrow">Branch schedule</p><h2>Schedule class · {branch.name}</h2></div><button type="button" className="icon-button" onClick={close} aria-label="Close"><X size={19} /></button></div>{error && <div className="form-error" role="alert">{error}</div>}<label>Class name<input name="title" required maxLength={160} autoFocus /></label><label>Trainer<select name="trainer"><option value="">Unassigned</option>{trainers.map((trainer) => <option key={trainer.id} value={trainer.id}>{trainer.name}</option>)}</select></label><label>Description<textarea name="description" maxLength={2000} rows={2} /></label><div className="field-pair"><label>Starts<input name="starts" type="datetime-local" defaultValue={defaults.start} required /></label><label>Ends<input name="ends" type="datetime-local" defaultValue={defaults.end} required /></label></div><label>Capacity<input name="capacity" type="number" min="1" max="1000" defaultValue="20" required /></label><label><input name="waitlist" type="checkbox" defaultChecked /> Enable waitlist</label><div className="modal-note"><ShieldCheck size={17} />Only active trainers assigned to this branch are offered. The backend checks both again.</div><div className="modal-actions"><button type="button" className="secondary-button" onClick={close}>Cancel</button><button className="primary-button" disabled={busy}>{busy ? "Scheduling…" : "Schedule class"}</button></div></form></div>;
}

function BranchReasonModal({ title, text, confirm, close, save }: { title: string; text: string; confirm: string; close: () => void; save: (reason: string) => Promise<void> }) {
  const [busy, setBusy] = useState(false); const [error, setError] = useState<string | null>(null);
  async function submit(event: FormEvent<HTMLFormElement>) { event.preventDefault(); setBusy(true); setError(null); try { await save(String(new FormData(event.currentTarget).get("reason"))); } catch (reason) { setError(reason instanceof Error ? reason.message : "The branch action could not be completed."); } finally { setBusy(false); } }
  return <div className="modal-layer" role="dialog" aria-modal="true" aria-label={title}><button className="modal-scrim" onClick={close} aria-label="Close dialog" /><form className="modal-card branch-action-modal" onSubmit={submit}><div className="modal-heading"><span><Building2 size={21} /></span><div><p className="eyebrow">Audited branch status</p><h2>{title}</h2></div><button type="button" className="icon-button" onClick={close} aria-label="Close"><X size={19} /></button></div><p>{text}</p>{error && <div className="form-error" role="alert">{error}</div>}<label>Audit reason<textarea name="reason" required minLength={5} maxLength={500} /></label><div className="modal-actions"><button type="button" className="secondary-button" onClick={close}>Cancel</button><button className="primary-button" disabled={busy}>{busy ? "Saving…" : confirm}</button></div></form></div>;
}

function BranchDeleteModal({ branch, close, save }: { branch: OperationBranch; close: () => void; save: (reason: string) => Promise<void> }) {
  const [busy, setBusy] = useState(false); const [error, setError] = useState<string | null>(null); const [confirmation, setConfirmation] = useState("");
  async function submit(event: FormEvent<HTMLFormElement>) { event.preventDefault(); setBusy(true); setError(null); try { await save(String(new FormData(event.currentTarget).get("reason"))); } catch (reason) { setError(reason instanceof Error ? reason.message : "The branch could not be deleted."); } finally { setBusy(false); } }
  return <div className="modal-layer" role="dialog" aria-modal="true" aria-label={`Delete ${branch.name}`}><button className="modal-scrim" onClick={close} aria-label="Close dialog" /><form className="modal-card branch-action-modal" onSubmit={submit}><div className="modal-heading"><span><Trash2 size={21} /></span><div><p className="eyebrow">Safe branch removal</p><h2>Delete {branch.name}</h2></div><button type="button" className="icon-button" onClick={close} aria-label="Close"><X size={19} /></button></div><div className="form-error">Only a non-primary branch with no linked members, staff, plans, memberships, classes, attendance or payments can be deleted. Otherwise deactivate it.</div>{error && <div className="form-error" role="alert">{error}</div>}<label>Type branch code <strong>{branch.code}</strong><input value={confirmation} onChange={(event) => setConfirmation(event.target.value)} autoComplete="off" required /></label><label>Audit reason<textarea name="reason" required minLength={5} maxLength={500} /></label><div className="modal-actions"><button type="button" className="secondary-button" onClick={close}>Cancel</button><button className="danger-button" disabled={busy || confirmation !== branch.code}>{busy ? "Deleting…" : "Delete unused branch"}</button></div></form></div>;
}
function BranchModal({ data, close }: { data: OperationData; close: () => void }) {
  const [timezone, setTimezone] = useState(data.gymTimezone);
  return <Modal title="Add branch" icon={Building2} close={close} save={(d) => data.onCreateBranch({ name: String(d.get("name")), code: String(d.get("code")), email: String(d.get("email")) || undefined, phone: String(d.get("phone")) || undefined, timezone: String(d.get("timezone")), is_primary: d.get("primary") === "on" })}><label>Name<input name="name" required autoFocus /></label><label>Code<input name="code" required pattern="[A-Za-z0-9_-]+" /></label><div className="field-pair"><label>Email<input name="email" type="email" /></label><label>Phone<input name="phone" /></label></div><SearchableSelect label="Timezone" name="timezone" options={timezoneOptions} value={timezone} onChange={setTimezone} placeholder="Search IANA timezone" /><label><input name="primary" type="checkbox" /> Primary branch</label></Modal>;
}
function PlanModal({ data, close }: { data: OperationData; close: () => void }) { return <Modal title="Add membership plan" icon={CircleDollarSign} close={close} save={(d) => data.onCreatePlan({ name: String(d.get("name")), code: String(d.get("code")), description: String(d.get("description")) || undefined, branch_id: String(d.get("branch")) || undefined, billing_interval: String(d.get("interval")) as NewOperationPlan["billing_interval"], interval_count: Number(d.get("count")), price_amount_minor: decimalToMinor(String(d.get("price"))), joining_fee_minor: decimalToMinor(String(d.get("fee") || "0")), duration_days: String(d.get("duration")) ? Number(d.get("duration")) : undefined, trial_days: String(d.get("trial")) ? Number(d.get("trial")) : undefined, currency: data.baseCurrency, status: "active" })}><div className="field-pair"><label>Name<input name="name" required autoFocus /></label><label>Code<input name="code" required /></label></div><label>Description<textarea name="description" rows={2} maxLength={5000} /></label><label>Branch<select name="branch"><option value="">All branches</option>{data.branches.map((v) => <option key={v.id} value={v.id}>{v.name}</option>)}</select></label><div className="field-pair"><label>Interval<select name="interval"><option value="one_time">One time</option><option value="weekly">Weekly</option><option value="monthly">Monthly</option><option value="quarterly">Quarterly</option><option value="yearly">Yearly</option></select></label><label>Every<input name="count" type="number" min="1" max="52" defaultValue="1" required /></label></div><div className="field-pair"><label>Price ({data.baseCurrency})<input name="price" inputMode="decimal" required /></label><label>Joining fee<input name="fee" inputMode="decimal" defaultValue="0" /></label></div><div className="field-pair"><label>Fixed duration (days)<input name="duration" type="number" min="1" max="3650" placeholder="No fixed expiry" /></label><label>Trial days<input name="trial" type="number" min="0" max="365" defaultValue="0" /></label></div></Modal>; }
function MembershipModal({ data, close }: { data: OperationData; close: () => void }) { return <Modal title="Create membership" icon={Dumbbell} close={close} save={(d) => data.onCreateMembership({ member_id: String(d.get("member")), plan_id: String(d.get("plan")), branch_id: String(d.get("branch")) || undefined, starts_at: String(d.get("starts")), ends_at: String(d.get("ends")) || undefined, status: String(d.get("status")) as "active" | "pending", auto_renew: d.get("renew") === "on" })}><label>Member<select name="member">{data.members.map((v) => <option key={v.id} value={v.id}>{v.name} · Member Code {v.memberCode}</option>)}</select></label><label>Plan<select name="plan">{data.plans.filter((v) => v.status === "active").map((v) => <option key={v.id} value={v.id}>{v.name} · {cash(v.priceMinor, v.currency)}</option>)}</select></label><label>Branch<select name="branch"><option value="">Plan/default branch</option>{data.branches.map((v) => <option key={v.id} value={v.id}>{v.name}</option>)}</select></label><div className="field-pair"><label>Starts<input name="starts" type="date" defaultValue={new Date().toISOString().slice(0, 10)} required /></label><label>End date override<input name="ends" type="date" /></label></div><label>Status<select name="status"><option value="active">Active</option><option value="pending">Pending</option></select></label><label><input name="renew" type="checkbox" defaultChecked /> Auto renew</label></Modal>; }

function EditModal({ title, close, save, children }: { title: string; close: () => void; save: (data: FormData) => Promise<void>; children: React.ReactNode }) { const [busy, setBusy] = useState(false); const [error, setError] = useState<string | null>(null); async function submit(event: FormEvent<HTMLFormElement>) { event.preventDefault(); setBusy(true); setError(null); try { await save(new FormData(event.currentTarget)); close(); } catch (reason) { setError(reason instanceof Error ? reason.message : "The update could not be saved."); } finally { setBusy(false); } } return <div className="modal-layer" role="dialog" aria-modal="true" aria-label={title}><button className="modal-scrim" onClick={close} aria-label="Close dialog" /><form className="modal-card" onSubmit={submit} autoComplete="off"><div className="modal-heading"><span><Pencil size={21} /></span><div><p className="eyebrow">Audited tenant update</p><h2>{title}</h2></div><button type="button" className="icon-button" onClick={close} aria-label="Close"><X size={19} /></button></div>{error && <div className="form-error" role="alert">{error}</div>}{children}<div className="modal-note"><ShieldCheck size={17} />The selected gym, actor and reason are written to the audit trail.</div><div className="modal-actions"><button type="button" className="secondary-button" onClick={close}>Cancel</button><button disabled={busy} className="primary-button" type="submit">{busy ? "Saving…" : "Save changes"}</button></div></form></div>; }

function EditBranchModal({ data, branch, close }: { data: OperationData; branch: OperationBranch; close: () => void }) {
  const [timezone, setTimezone] = useState(branch.timezone ?? data.gymTimezone);
  return <EditModal title={`Edit ${branch.name}`} close={close} save={(form) => data.onUpdateBranch(branch.id, { name: String(form.get("name")), code: String(form.get("code")), email: String(form.get("email")) || null, phone: String(form.get("phone")) || null, timezone: String(form.get("timezone")), status: String(form.get("status")) as "active" | "inactive", is_primary: form.get("primary") === "on", reason: String(form.get("reason")) })}><div className="field-pair"><label>Name<input name="name" defaultValue={branch.name} required /></label><label>Code<input name="code" defaultValue={branch.code} required pattern="[A-Za-z0-9_-]+" /></label></div><div className="field-pair"><label>Email<input name="email" type="email" defaultValue={branch.email ?? ""} /></label><label>Phone<input name="phone" defaultValue={branch.phone ?? ""} /></label></div><SearchableSelect label="Timezone" name="timezone" options={timezoneOptions} value={timezone} onChange={setTimezone} placeholder="Search IANA timezone" /><label>Status<select name="status" defaultValue={branch.status}><option value="active">Active</option><option value="inactive">Inactive</option></select></label><label><input name="primary" type="checkbox" defaultChecked={branch.isPrimary} /> Primary branch</label><label>Audit reason<textarea name="reason" required maxLength={500} /></label></EditModal>;
}

function EditPlanModal({ data, plan, close }: { data: OperationData; plan: OperationPlan; close: () => void }) { return <EditModal title={`Edit ${plan.name}`} close={close} save={(form) => data.onUpdatePlan(plan.id, { name: String(form.get("name")), code: String(form.get("code")), description: String(form.get("description")) || null, branch_id: String(form.get("branch")) || null, price_amount_minor: decimalToMinor(String(form.get("price"))), currency: data.baseCurrency, duration_days: String(form.get("duration")) ? Number(form.get("duration")) : null, trial_days: Number(form.get("trial") || 0), status: String(form.get("status")) as "active" | "inactive", reason: String(form.get("reason")) })}><div className="field-pair"><label>Name<input name="name" defaultValue={plan.name} required /></label><label>Code<input name="code" defaultValue={plan.code} required /></label></div><label>Description<textarea name="description" rows={2} maxLength={5000} defaultValue={plan.description ?? ""} /></label><label>Branch<select name="branch" defaultValue={plan.branchId ?? ""}><option value="">All branches</option>{data.branches.map((branch) => <option key={branch.id} value={branch.id}>{branch.name}</option>)}</select></label><div className="field-pair"><label>Future price ({data.baseCurrency})<input name="price" defaultValue={(plan.priceMinor / 100).toFixed(2)} inputMode="decimal" required /></label><label>Status<select name="status" defaultValue={plan.status}><option value="active">Active</option><option value="inactive">Inactive</option></select></label></div><div className="field-pair"><label>Fixed duration (days)<input name="duration" type="number" min="1" max="3650" defaultValue={plan.durationDays ?? ""} placeholder="No fixed expiry" /></label><label>Trial days<input name="trial" type="number" min="0" max="365" defaultValue={plan.trialDays} /></label></div><small>Existing memberships keep their accepted price snapshot and expiry date.</small><label>Audit reason<textarea name="reason" required maxLength={500} /></label></EditModal>; }

function EditMembershipModal({ data, membership, memberName, close }: { data: OperationData; membership: OperationMembership; memberName: string; close: () => void }) { return <EditModal title={`Edit ${memberName} membership`} close={close} save={(form) => data.onUpdateMembership(membership.id, { status: String(form.get("status")) as OperationMembership["status"], ends_at: String(form.get("ends_at")) || null, next_billing_at: String(form.get("next_billing_at")) || null, auto_renew: form.get("auto_renew") === "on", cancellation_reason: String(form.get("cancellation_reason")) || null, reason: String(form.get("reason")) })}><label>Status<select name="status" defaultValue={membership.status}><option value="pending">Pending</option><option value="active">Active</option><option value="paused">Paused</option><option value="cancelled">Cancelled</option><option value="expired">Expired</option></select></label><div className="field-pair"><label>Ends<input name="ends_at" type="date" defaultValue={membership.endsAt?.slice(0, 10) ?? ""} /></label><label>Next billing<input name="next_billing_at" type="date" defaultValue={membership.nextBillingAt?.slice(0, 10) ?? ""} /></label></div><label><input name="auto_renew" type="checkbox" defaultChecked={membership.autoRenew} /> Auto renew</label><label>Cancellation reason<textarea name="cancellation_reason" maxLength={1000} placeholder="Required when cancelling" /></label><label>Audit reason<textarea name="reason" required maxLength={500} /></label></EditModal>; }
