[supervisord]
nodaemon=true
logfile=/dev/null
logfile_maxbytes=0
pidfile=/tmp/supervisor/supervisord.pid
childlogdir=/tmp/supervisor

[program:php-fpm]
command=php-fpm -F
autostart=true
autorestart=true
startsecs=1
stopasgroup=true
killasgroup=true
stdout_logfile=/dev/stdout
stdout_logfile_maxbytes=0
stderr_logfile=/dev/stderr
stderr_logfile_maxbytes=0

[program:caddy]
command=caddy run --config /etc/caddy/Caddyfile --adapter caddyfile
autostart=true
autorestart=true
startsecs=1
stopasgroup=true
killasgroup=true
environment=XDG_DATA_HOME="/tmp/caddy/data",XDG_CONFIG_HOME="/tmp/caddy/config"
stdout_logfile=/dev/stdout
stdout_logfile_maxbytes=0
stderr_logfile=/dev/stderr
stderr_logfile_maxbytes=0
